//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendancetable
    {
        public int id { get; set; }
        public int interneeid { get; set; }
        public System.DateTime reportDatetime { get; set; }
        public System.DateTime leaveDatetime { get; set; }
        public int statusid { get; set; }
    
        public virtual attendancestatustable attendancestatustable { get; set; }
        public virtual interneetable interneetable { get; set; }
    }
}
