//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IASDBEntities : DbContext
    {
        public IASDBEntities()
            : base("name=IASDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendancestatustable> attendancestatustables { get; set; }
        public virtual DbSet<attendancetable> attendancetables { get; set; }
        public virtual DbSet<batchtable> batchtables { get; set; }
        public virtual DbSet<interneetable> interneetables { get; set; }
        public virtual DbSet<managerstable> managerstables { get; set; }
        public virtual DbSet<supervisortable> supervisortables { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
    }
}
