//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class interneetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public interneetable()
        {
            this.attendancetables = new HashSet<attendancetable>();
        }
    
        public int id { get; set; }
        public int batchid { get; set; }
        public int userid { get; set; }
        public int supervisorid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendancetable> attendancetables { get; set; }
        public virtual batchtable batchtable { get; set; }
        public virtual supervisortable supervisortable { get; set; }
        public virtual usertable usertable { get; set; }
    }
}
